const mockupMeals = [
  {
    name: 'Steak',
    photo: 'https://st.depositphotos.com/1020804/1448/i/950/depositphotos_14480443-stock-photo-beef-steak.jpg',
    description: 'served with mashed potatos',
    time: 25,
    low_calorie: false,
    vegetarian: false,
    pescatarian: false,
    vegan: false,
    halal: false,
    spicy: false,
    easy_prep: true,
    easy_cleanup: true,
  },
  {
    name: 'Vegetables',
    photo: 'https://st.depositphotos.com/1020804/1448/i/950/depositphotos_14480443-stock-photo-beef-steak.jpg',
    description: 'stir-fryed to perfection',
    time: 45,
    low_calorie: true,
    vegetarian: true,
    pescatarian: true,
    vegan: true,
    halal: true,
    spicy: false,
    easy_prep: true,
    easy_cleanup: true,
  },
  {
    name: 'Crispy Parmesan Chicken',
    photo: 'https://st.depositphotos.com/1020804/1448/i/950/depositphotos_14480443-stock-photo-beef-steak.jpg',
    description: 'with Garlic Herb Couscous & Lemony Roasted Carrots',
    time: 25,
    low_calorie: false,
    vegetarian: false,
    pescatarian: false,
    vegan: false,
    halal: true,
    spicy: true,
    easy_prep: false,
    easy_cleanup: false,
  },
  {
    name: 'Zucchini & Tomato Flatbreads',
    photo: 'https://st.depositphotos.com/1020804/1448/i/950/depositphotos_14480443-stock-photo-beef-steak.jpg',
    description: 'with Lemon Ricotta, Fresh Herbs, Honey & Chili Flakes',
    time: 35,
    low_calorie: true,
    vegetarian: true,
    pescatarian: true,
    vegan: true,
    halal: true,
    spicy: false,
    easy_prep: true,
    easy_cleanup: true,
  },
];

export default mockupMeals;
